### ISSUE TITLE
Container Orientation

### ISSUE THREAD

**Issue by thomascorrie** [thomascorrie/Miscellany#1]
Container orientation needs reviewing

**Comment by thomascorrie** [comment]
The problem is that CromulentBisgetti uses a coordinate system with XZ as the base plane and Y as the vertical direction. The Y and Z values for the coordinates and packed dimension for items need to be swapped before exposing in Dynamo. See image from EB-AFIT algorithm paper:
![orientation-diagram](https://user-images.githubusercontent.com/6866618/46263172-96c70800-c503-11e8-904a-5df8be405733.PNG)

**Comment by Vanman989** [comment]
Could your nodes be used for 2d packing? If the z values were just 0? Wondering if I could then pack rectangles and get there centre points for locations to pack views on sheets. I would be inputting bounding boxes. Not sure what your exact container input formula is that the nodes take. Sorry for the comment in the wrong place. Still understanding git hub and couldn't figure out how else to ask.

I'm not at work to try it with 2d. What node is going into the algorithm inputs? Do you have a YouTube video or some example graphs set up?

**Comment by thomascorrie** [comment]
@Vanman989 no worries, I have created this query as a new issue #11 and I will answer there
